language: php
php:
  - 5.6
  - hhvm
matrix:
  allow_failures:
  - php: 5.6
  - php: hhvm
env:
  - MAGENTO_VERSION=magento-mirror-1.9.2.4
script:
  - curl -sSL https://gist.githubusercontent.com/StudioForty9/8a03200755c8b9e01cf4/raw/9fb1d82c103822bb26ba8053da65ca636ff10331/recaptcha-install.sh | bash
